### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by lichongbin** [jasonleaster/FaceDetection#10]
If DEBUG_MODEL is True, the following code in cascade.py will crash:
self._mat = numpy.zeros((self.haar.featuresNum, tot_samples))

**Comment by jasonleaster** [comment]
"Memory Error" ?
Maybe, the RAM of your machine is too small to run this project.
Here I will give two suggestion to you:
1. decrease the number of the samples in training set
2. increase RAM of your machine or workstation.

**Comment by lichongbin** [comment]
Do you really complete this project? If so, why do you place the following statement in cascade.py?
        raise ("Unfinished")

**Comment by lichongbin** [comment]
I have set the DEBUG_MODEL to False to avoid this error.

**Comment by jasonleaster** [comment]
I never said "I completed this".  If you are not trying to contribute to this project or RTFSC, please close this issure. thx

**Comment by chuangcai** [comment]
> I have set the DEBUG_MODEL to False to avoid this error.

请问您是否已经解决了？可以分享一下您的完整代码吗？十分感谢！
