### ISSUE TITLE
I have a problem to ask author  

### ISSUE THREAD

**Issue by JimZock** [jasonleaster/FaceDetection#12]
作者
不好意思 現在我運行 trainingAdaboost.py 的時候已經可以訓練也保存完成了
但是在執行EFace.py的時候會產生 ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all() 這樣的error 
請問作者也有發生過同樣的問題？

**Comment by jasonleaster** [comment]
检查一下python的版本，利用python基础知识单步调试排错
