### ISSUE TITLE
关于检测的结果的错误问题

### ISSUE THREAD

**Issue by TTTREE** [jasonleaster/FaceDetection#13]
你好，感谢你的项目。我在使用提供的model测试图片时，得到的结果
![image](https://user-images.githubusercontent.com/37862384/57978252-07437a80-7a3c-11e9-865e-78d9d7bbfb42.png)
请问是哪里出了问题吗？

**Comment by jasonleaster** [comment]
不同的训练样本，得到的模型参数会影响检测结果

**Comment by jasonleaster** [comment]
> 你好，感谢你的项目。我在使用提供的model测试图片时，得到的结果
> ![image](https://user-images.githubusercontent.com/37862384/57978252-07437a80-7a3c-11e9-865e-78d9d7bbfb42.png)
> 请问是哪里出了问题吗？

不同的训练样本，得到的模型参数不同，都会影响检测结果。多读源代码深入理解问题

**Comment by chuangcai** [comment]
> 你好，感谢你的项目。我在使用提供的model测试图片时，得到的结果
> ![image](https://user-images.githubusercontent.com/37862384/57978252-07437a80-7a3c-11e9-865e-78d9d7bbfb42.png)
> 请问是哪里出了问题吗？
您好，请问您的问题解决了吗？ 可以请教一下如何解决的？ 可否提供一下改正后的代码  学习一下，十分感谢！！！

**Comment by chuangcai** [comment]
> 你好，感谢你的项目。我在使用提供的model测试图片时，得到的结果
> ![image](https://user-images.githubusercontent.com/37862384/57978252-07437a80-7a3c-11e9-865e-78d9d7bbfb42.png)
> 请问是哪里出了问题吗？

您好，请问您的问题解决了吗？ 可以请教一下如何解决的？ 可否提供一下改正后的代码 学习一下，十分感谢！！！

**Comment by TTTREE** [comment]
> 
> 
> > 你好，感谢你的项目。我在使用提供的model测试图片时，得到的结果
> > ![image](https://user-images.githubusercontent.com/37862384/57978252-07437a80-7a3c-11e9-865e-78d9d7bbfb42.png)
> > 请问是哪里出了问题吗？
> 
> 您好，请问您的问题解决了吗？ 可以请教一下如何解决的？ 可否提供一下改正后的代码 学习一下，十分感谢！！！

没有解决，我放弃了。。

**Comment by TTTREE** [comment]
> 
> 
> > 你好，感谢你的项目。我在使用提供的model测试图片时，得到的结果
> > ![image](https://user-images.githubusercontent.com/37862384/57978252-07437a80-7a3c-11e9-865e-78d9d7bbfb42.png)
> > 请问是哪里出了问题吗？
> 
> 不同的训练样本，得到的模型参数不同，都会影响检测结果。多读源代码深入理解问题

我用的你提供的预训练好的model，测试demo图片

**Comment by TTTREE** [comment]
> 
> 
> > > 你好，感谢你的项目。我在使用提供的model测试图片时，得到的结果
> > > ![image](https://user-images.githubusercontent.com/37862384/57978252-07437a80-7a3c-11e9-865e-78d9d7bbfb42.png)
> > > 请问是哪里出了问题吗？
> > 
> > 
> > 您好，请问您的问题解决了吗？ 可以请教一下如何解决的？ 可否提供一下改正后的代码 学习一下，十分感谢！！！
> 
> 没有解决，我放弃了。。

不过，你现在用的是python3吗，改成python2.7效果会变好一些
