### ISSUE TITLE
关于弱分类器的阈值选择问题

### ISSUE THREAD

**Issue by lizhiyuanUSTC** [jasonleaster/FaceDetection#3]
你好，在实现弱分类器的时候，你用(miuPos + miuNeg)/2作为弱分类器的阈值，这个阈值是一个合理的选择吗？我修改了你的这部分代码，在特征里找了一些离散值来寻找最优的阈值，但是训练的时候选择到的特征和论文描述不符合

**Comment by jasonleaster** [comment]
@lizhiyuanUSTC  是的，我用的是(miuPos + miuNeg)/2 就是两者均值的“中点”，实际上可以自己“动态的去寻找”一个从训练过程来看是最优的弱分类器阈值，有很多弱分类器就是这么实现的，也有和我一样，用这个“中点”值来做的。至于你说的“训练得到的特征和论文描述的不一样”，是这个样子的，当时我自己动手写整个项目的时候，能够参考的实际实现非常的少，当时很幸运找到了一个学校的课程实现AdaBoost的代码，用matlab写的，我反复研究用Python写了E-Face，论文中的那个人脸特征组合图只是一个“示意图”，不同的训练样本，不同的训练整幅样本比例完全会得到不同的最后的强分类器，即可视化后你看到的那个“类似于人脸的图片”。

至于最后的实验结果，都是E-Face跑出来的，都是真实的。（自证清白一下，毕竟搞CV水太深，有些人浑水摸鱼）

如果你对E-Face有更深的兴趣可以欢迎继续交流

希望我的工作对你有帮助 : )

**Comment by jasonleaster** [comment]
@lizhiyuanUSTC 
此外，你可以看到我在实现基础的AdaBoost的算法的时候，其中弱分类器就是用的你说的“找最优的threshold去做为弱分类器的阈值”。

[戳我 =.=   弱分类器的实现之一](https://github.com/jasonleaster/Machine_Learning/blob/master/Adaboost/decisionStump.py)

你能在 https://github.com/jasonleaster/Machine_Learning/blob/master/Adaboost/ 找到我对于AdaBoost算法的实现。

**Comment by lizhiyuanUSTC** [comment]
@jasonleaster 很感谢你的工作，帮助我理清了很多级联分类器的思路，抱歉我没说清楚，并没有怀疑你的意思，论文里有提到：The first feature measures the difference in intensity between the region of the eyes and a region across the upper cheeks。我看到你的doc里写的选到的第一个特征和这个差不多，我想可能这个特征就是比较重要的，我以为是训练集不管怎么样都会第一个选到这个特征

另外，我看到你model里adaboost_classifier.cache0文件里第一个特征是第23363个特征，doc里讲到第一个特征是5287，adaboost_classifier.cache0文件是后来又训练过了吗

**Comment by lizhiyuanUSTC** [comment]
@jasonleaster 对了，我大概明白了，开始你只用了四种haar特征，后来用了五种
