### ISSUE TITLE
请问一下adaboost.py文件中，weakernum为什么是文件长度除以4？这个文件是什么文件？为什么除以4呢？为什么把这个值赋给limit呢？

### ISSUE THREAD

**Issue by BigFaceKittie** [jasonleaster/FaceDetection#4]

**Comment by jasonleaster** [comment]
Hi, @BigFaceKittie 

首先很抱歉，在我的代码里面出现了magic number ：）当时程序实现，debug的时候，可能是很累了。没有再注意到这个细节，造成代码质量的下降或者困扰，表示抱歉

是这样的，大部分你说的4这个magic number，其实是指的我的机器的CPU核心数。我把计算量大的处理过程，并行的划分到4个进程，尝试利(za)用(gan)自己机器的性能，充分的利用计算资源，加速计算过程。每个进程计算完之后，会把特征值写入到一个临时文件中(叫它 cache file也好 tmp file也好)，4个进程，于是就有4个 cache file，最后合并四个临时文件，得到完整的特征值。

大部分出现在这个函数内
```
python
def getCachedAdaBoost(mat = None, label = None, filename = "", limit = 0):
```
顾名思义，就是从临时文件，合成（“恢复”）成最终”完整" 特征值文件的过程。
因为调试过程，训练过程，在开发中有很多很多次，而且非常耗时（一般等12个小时很正常），所以为了避免一些重复计算的过程，我也选择了对“已经计算过的特征值”，不再重复计算，暂存到文件中。

希望我的回答能解答你的困惑，对你的研究有所帮助

**Comment by BigFaceKittie** [comment]
太感谢了！谢谢您的不吝指导！
