### ISSUE TITLE
haarFeature.py相关问题咨询

### ISSUE THREAD

**Issue by sheldon-iceland** [jasonleaster/FaceDetection#6]
请问vecRectSum中idxVector具体含义是什么？idx1,idx2,idx3,idx4代表的是什么呢？idx1,idx2,idx3,idx4计算式是何含义?
希望大神能抽空解除下我的疑惑，万分焦急！万分感谢！

**Comment by jasonleaster** [comment]
先建议你多读几遍能google到的相关文献，特别是Haar特征向量化方面的。因为最近工作实在太忙了，没有时间回顾之前的项目细节

**Comment by sheldon-iceland** [comment]
诚挚建议你以后写代码多些注释
