### ISSUE TITLE
When i run the trainingAdaBoost.py there is a error happen 

### ISSUE THREAD

**Issue by sl6256543** [jasonleaster/FaceDetection#8]
Like this . I know i have the train datas, so it should build the featuretrain_cache.npy.  But none. ido't understand why 
![_20180322092918](https://user-images.githubusercontent.com/16289338/37746143-ae3fe8d6-2db3-11e8-9832-f091aa5a80ac.png)

**Comment by jasonleaster** [comment]
调试技巧，发生异常断点事前，尝试通过python的shell交互界面打印当前目录路径，确认python的执行路径当前路径在项目文件夹，而不是python的安装路径。
PWD
